# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# TODO: Set up subdirectories properly so this contains both iOS and Android and doesn't need to be cp'd in

default_platform(:ios)
setup_ci

org, repo = ENV["GITHUB_REPOSITORY"].split("/")
match_org, match_repo = ENV["MATCH_REPOSITORY"].split("/")

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "development")
    build_app(workspace: "ios/App/App.xcworkspace", scheme: "App")
    upload_to_testflight
  end

  desc "Push a new build to the App Store"
  lane :beta do
    match(type: "appstore")
    build_app(workspace: "ios/App/App.xcworkspace", scheme: "App")
    upload_to_app_store
  end

  lane :init_ci do
    github_action(
      api_token: ENV["GH_PAT"],
      org: org,
      repo: repo,
      match_org: match_org,
      match_repo: match_repo,
    )
  end
end
