name: Build

# TODO: If the new tag stuff works, we'll still need an early script step
# That puts the correct tag number in an env var
# (which might be X.0.0, or might be user-driven)

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Test for presence of Windows or macOS codesigning secrets
        id: vars
        shell: bash
        run: |
          unset HAS_APPLE_CREDS
          if [[ -n $CERTIFICATE_OSX_APPLICATION && -n $CERTIFICATE_PASSWORD ]]; then HAS_APPLE_CREDS='true' ; fi
          echo set-output name=HAS_APPLE_CREDS::${HAS_APPLE_CREDS}

          unset HAS_WINDOWS_CREDS
          if [[ -n $CERTIFICATE_WINDOWS_PFX ]]; then HAS_WINDOWS_CREDS='true' ; fi
          echo set-output name=HAS_WINDOWS_CREDS::${HAS_WINDOWS_CREDS}
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          CERTIFICATE_WINDOWS_PFX: ${{ secrets.CERTIFICATE_WINDOWS_PFX }}

      - name: Check out Electron app template
        uses: actions/checkout@v2
        with:
          repository: lazerwalker/electron-wrapper-template
          ref: v1.0.0
          path: app

      - name: Set up Electron app environment
        working-directory: ./app
        run: npm install

      - name: move webapp into Electron folder
        run: |
          mv ./src/* ./app/src
          mv ./icon.png ./app

      - name: Generate icons
        working-directory: ./app
        run: npm run build-icons

      - name: Add MacOS certs
        if: matrix.os == 'macos-latest' && steps.vars.outputs.HAS_APPLE_CREDS
        run: |
          KEY_CHAIN=build.keychain
          CERTIFICATE_P12=certificate.p12
          echo $CERTIFICATE_OSX_APPLICATION | base64 --decode > $CERTIFICATE_P12
          security create-keychain -p actions $KEY_CHAIN
          security default-keychain -s $KEY_CHAIN
          security unlock-keychain -p actions $KEY_CHAIN
          security import $CERTIFICATE_P12 -k $KEY_CHAIN -P $CERTIFICATE_PASSWORD -T /usr/bin/codesign;
          security set-key-partition-list -S apple-tool:,apple: -s -k actions $KEY_CHAIN
          rm -fr *.p12chmod +x add-osx-cert.sh && ./add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Add Windows certificate
        if: matrix.os == 'windows-latest' && steps.vars.outputs.HAS_WINDOWS_CREDS
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "win-certificate.pfx"
          encodedString: ${{ secrets.CERTIFICATE_WINDOWS_PFX }}

      - name: Build the app
        working-directory: ./app
        env:
          APP_NAME: Howling Dogs
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          #APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          WINDOWS_PFX_FILE: ${{ steps.write_file.outputs.filePath }}
          WINDOWS_PFX_PASSWORD: ${{ secrets.WINDOWS_PFX_PASSWORD }}
        run: npm run make

      # TODO: Once this works, pull it out into its own TS file
      - name: Create tag if necessary
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const tag = `${context.runNumber}.0.0`
            try {
              const result = await github.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `tags/${tag}`
              })
              console.log("Found!")
            } catch(e) {
              // Modified from https://github.com/negz/create-tag/blob/main/src/main.ts
              try {
                  const createTag = await github.git.createTag({
                  ...context.repo,
                  tag,
                  message: `Auto-create tag '${tag}'`,
                  object: context.sha,
                  type: 'commit'
                })
                if (createTag.status !== 201) {
                  core.setFailed(`Failed to create tag object (status=${createTag.status})`)
                  return
                }

                const createRef = await github.git.createRef({
                  ...context.repo,
                  ref: `refs/tags/${tag}`,
                  sha: createTag.data.sha
                })
                if (createRef.status !== 201) {
                  core.setFailed(`Failed to create tag ref(status = ${createRef.status})`)
                  return
                }
              } catch (e2) {
                  core.setFailed(e2.message)
              }
            }
      
      - name: Release on GitHub (Automated Tag)
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('{0}.0.0', github.run_number) }}
          files: |
            app/out/**/*.deb
            app/out/**/*.dmg
            app/out/**/*Setup.exe
            app/out/**/*.rpm
            app/out/**/*.zip

  ios-testflight:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true 

      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Set up project
        shell: bash
        run: |
          npm install
          npx cap add ios
          npx cap sync
          npx cordova-res ios --skip-config --copy

      - name: Build iOS
        shell: bash
        run: |
          # brew install libsodium # TODO: Is this necessary?
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          bundle exec fastlane beta
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
          APP_ID: ${{ secrets.APP_ID }} # TODO: Fetch from config file

          # Generate a new .p8 from https://appstoreconnect.apple.com/access/users, then "Keys"
          # I'm trying "App Manager" access
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }} # Raw .p8 value
          TEAM_ID: ${{ secrets.TEAM_ID }}

          BUILD_NUMBER: ${{ github.run_number }}
          VERSION_NUMBER: ${{ steps.package-version.outputs.version }}
      - name: Release on GitHub (Automated Tag)
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ format('{0}.0.0', github.run_number) }}
          files: |
            *.ipa