name: iOS One-Time Setup

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Move config to root dir
        run: mv config/* .

      - name: Set game configuration
        run: |
          echo "APP_NAME=$(cat ./package.json | jq -r '.name')" >> $GITHUB_ENV
          echo "DISPLAY_NAME=$(cat ./package.json | jq -r '.displayName')" >> $GITHUB_ENV
          echo "DESCRIPTION=$(cat ./package.json | jq -r '.description')" >> $GITHUB_ENV
          echo "AUTHOR=$(cat ./package.json | jq -r '.author')" >> $GITHUB_ENV
          echo "VERSION=$(cat ./package.json | jq -r '.version')" >> $GITHUB_ENV
          echo "BUNDLE_ID=($(cat ./package.json | jq -r '.iOSBundleId') || $(cat ./package.json | jq -r '.bundleId')" >> $GITHUB_ENV
          echo "PUBLISH_ON_WEB=$(cat ./package.json | jq -r '.publishOnWeb')" >> $GITHUB_ENV
                
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true 

      - name: Build iOS
        shell: bash
        run: |
          bundle exec fastlane init_ci
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}

          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }} # Raw .p8 value
